global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - follow_redirects: true
      scheme: http
      timeout: 10s
      api_version: v2
      static_configs:
        - targets:
            - celestia-da-alertmanager:9093

rule_files:
  - /etc/prometheus/alerts/alert.rules

scrape_configs:
  # Prometheus metrics
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  # Otel Collector metrics
  - job_name: otel-collector
    static_configs:
      - targets:
          - celestia-da-otel-collector:8888
  # Celestia DA node metrics
  - job_name: celestia-da-node-metrics
    static_configs:
      - targets:
          - celestia-da-otel-collector:8889
