{
 "title": "Celestia DA node",
 "tags": [
  "celestia",
  "da"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "<table width=\"100%\" style=\"margin: 0px; border: 0px transparent; border-color: transparent\">\r\n<thead>\r\n    <td style=\"text-align:center\">\r\n      <a href=\"https://www.pops.one\" target=\"_blank\">\r\n      <img src=\"https://pops.one/img/logo.png\" /></td>\r\n      </a>\r\n  </tr>\r\n</thead>\r\n</table>\r\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "celestia_head",
   "type": "stat",
   "description": "celestia_head",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_head", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Celestia head",
   "type": "timeseries",
   "description": "Celestia head",
   "gridPos": { "h": 6, "w": 14, "x": 3, "y": 4 },
   "targets": [
    { "expr": "celestia_head", "legendFormat": "Celestia head" }
   ]
  },
  {
   "title": "Node uptime",
   "type": "stat",
   "description": "total time the node has been running",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_node_runtime_counter_in_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total synced headers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 3, "y": 10 },
   "targets": [
    { "expr": "celestia_total_synced_headers", "legendFormat": "Total synced header" }
   ]
  },
  {
   "title": "Synced header count",
   "type": "stat",
   "description": "Total synced header count",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_total_synced_headers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DAS",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_das_head_updated_counter",
     "legendFormat": "amount of times DAS'er advanced network head"
    },
    { "expr": "celestia_das_network_head", "legendFormat": "most recent network head" },
    {
     "expr": "celestia_das_sampled_chain_head",
     "legendFormat": "height of the sampled chain"
    },
    {
     "expr": "celestia_das_total_sampled_headers",
     "legendFormat": "total sampled headers"
    }
   ]
  },
  {
   "title": "Last das sampled",
   "type": "stat",
   "description": "Last das sample",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "celestia_das_latest_sampled_ts * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PFB count",
   "type": "stat",
   "description": "Total count of submitted PayForBlob transactions",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_pfb_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last PayForBlob ",
   "type": "stat",
   "description": "Last PayForBlob date and time",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "celestia_last_pfb_timestamp", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sampled header counter",
   "type": "stat",
   "description": "Sampled header counter for different width height",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_das_sampled_headers_counter",
     "legendFormat": "header width of {{header_width}}"
    }
   ]
  },
  {
   "title": "DA node logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{unit=~\"celestia-[lbf].*.service\"} |= ``"
    }
   ]
  }
 ]
}