{
 "title": "Celestia Bridge Dashboard",
 "description": "This dashboard provides a comprehensive view of key metrics from Celestia Bridge node. It offers insights into node performance, health and activity.",
 "tags": [
  "celestia",
  "DA",
  "bridge"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node_id",
    "query": {
     "query": "label_values(celestia_build_info,service_instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <br>\n    <img src=\"https://services.kjnodes.com/assets/images/logos/celestia.png\"><br><br>\n    <h1>Celestia Bridge Dashboard</h1>\n    <h5>⚡️ Powered by <a href=\"https://kjnodes.com\">kjnodes</a></h5>\n</div>"
   }
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>System</h2>\r\n</div>"
   }
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "celestia_build_info{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{service_namespace}}"
    }
   ]
  },
  {
   "title": "Node Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "celestia_build_info{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Build Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "celestia_build_info{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{semantic_version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_runtime_uptime_milliseconds_total{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_hdr_sync_loop_status_gauge{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks To Sync",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_hdr_sync_subjective_head_gauge{service_instance_id=\"$node_id\"} - celestia_hdr_store_head_height_gauge{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_hdr_store_head_height_gauge{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "celestia_hdr_store_head_height_gauge{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Network</h2>\r\n</div>"
   }
  },
  {
   "title": "Total Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_full_discovery_amount_of_peers{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "celestia_full_discovery_amount_of_peers{service_instance_id=\"$node_id\"}",
     "legendFormat": "full"
    }
   ]
  },
  {
   "title": "Archival Peers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_archival_discovery_amount_of_peers{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archival Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "celestia_archival_discovery_amount_of_peers{service_instance_id=\"$node_id\"}",
     "legendFormat": "archival"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<div style=\"text-align: center;\">\r\n    <br>\r\n    <h2>Blockchain</h2>\r\n</div>"
   }
  },
  {
   "title": "Block time",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "600 / round(increase(celestia_hdr_sync_subjective_head_gauge{service_instance_id=\"$node_id\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "stat",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(celestia_hdr_sync_subjective_head_gauge{service_instance_id=\"$node_id\"}[10m]))/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per minute",
   "type": "timeseries",
   "description": "Number of blocks produced last minute",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "increase(celestia_hdr_sync_subjective_head_gauge{service_instance_id=\"$node_id\"}[10m])/10",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Store Put Latency Distribution [1h]",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(celestia_eds_store_put_time_histogram_sum{service_instance_id=\"$node_id\"}[60m]) / rate(celestia_eds_store_put_time_histogram_count{service_instance_id=\"$node_id\"}[60m])",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Store Put Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(celestia_eds_store_put_time_histogram_sum{service_instance_id=\"$node_id\"}[5m])",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Store Put Operations / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "targets": [
    {
     "expr": "rate(celestia_eds_store_put_time_histogram_count{service_instance_id=\"$node_id\"}[5m]) * 60",
     "legendFormat": "eds_size={{eds_size}}"
    }
   ]
  },
  {
   "title": "Sent shrex/nd responses / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(celestia_shrex_nd_server_responses_total{service_instance_id=\"$node_id\"}[60m])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Sent shrex/eds responses / Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "rate(celestia_shrex_eds_server_responses_total{service_instance_id=\"$node_id\"}[60m])*60",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total number of headers served",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_hdr_p2p_exch_srvr_headers_served_counter_total{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Number of headers served",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 56 },
   "targets": [
    {
     "expr": "celestia_hdr_p2p_exch_srvr_headers_served_counter_total{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Total header message count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "celestia_hdr_p2p_sub_msg_num_counter_total{service_instance_id=\"$node_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total header message count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 56 },
   "targets": [
    {
     "expr": "celestia_hdr_p2p_sub_msg_num_counter_total{service_instance_id=\"$node_id\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}